"""
This type stub file was generated by pyright.
"""

def dict_map(input, keyMap): # -> dict[Unknown, Unknown]:
	'''Return a new dict from an input dict and a {'input_key': 'output_key'} mapping'''
	...

def snake_to_camel(**kwargs): # -> dict[Unknown, Unknown]:
	'''Return a new dict from kwargs with snake_case keys replaced by camelCase'''
	...

